project: mulesoft
users:
  - id: gbartoloni
    privileged: true
apps:
  - name: fcg-mule-test
    buildCommand: mavenBuildAndDeploy
    repoUrl: https://bitbucket.org/edpclivet/clivet-proc-employees.git
    credentialsId: workspace-token
sharedLibraryVersion: main