project: mulesoft
users:
  - id: gbartoloni
    privileged: true
apps:
  - name: fcg-mule-test
    buildCommand: mavenBuildAndDeployCH2
    repoUrl: https://github.com/gbartoloni-florence/fcg-mule-test.git